using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TeachersClass  {
    public string[] mrsPoppysQuestions;
    public string[] mrPonnyRainbowQuestions;
    public string[] mrNoruasQuestions;
    public TeachersClass() { 
     //string teacherName;
     mrPonnyRainbowQuestions = new string[] { "What is TCP?", "What is UDP?", "What is SOAP?", "What is a kernel thread?", "What is user thread?", "What is Mutex?", "What is semaphore?", "How does First come- First served scheduling algorithm work?", "How does Preemptive Short Job First scheduling algorithm work?", "How does Non-preemptive Short Job First scheduling algorithm work?", "How does Priority scheduling algorithm work?", "How does Round Robin scheduling algorithm work?", "What is OSI model?", "Transmission Control Protocol/IP Model?", "How does 3-way handshake work?", "What is network hardware and servers?", "What is Subnetting?", "What are Network types?", "What is Broadcast?", "What is Tor?", "What is Proxy pattern?", "What is VPN?", "What is VLAN?", "What is HTTP?", "How does HTTP GET work?", "How does HTTP POST work?", "How does HTTP HEAD work?", "What is Telnet?", "What is TCP/IP protocol?", "What is SSH?", "What is encryption?", "What is hashing?", "What is salting? ", "What is PGP?", "What is GPG?", "What are SQL injections?", "What is thread safety? ", "How you ensure thread safety? ", "What is brute forcing?", "What are honeypots?", "What is port scanning? ", "What is ACID?", "What is normalization?", "What are normalization forms?", "What is a Database? ", "Why do we normalize the database? ", "What is CPU?", "What is motherboard" };
     mrsPoppysQuestions = new string[] { "What is an artifact?","What is Object model?","What is Domain model?","What is Design Class Diagram?", "What is difference between Object and Domain model?", "What is Sequence Diagram?", "What Is Systems Sequence Diagram?", "How can you assure artifacts quality?", "How can you assure traceability?", "What is the difference between Use Case and User story?", "What is the difference between persona and actor?", "What is UML?", "What is Use Case?", "What is persona?", "What is scenario?", "What is Business model?", "What is Business case?", "What is FURPS+?", "What is a User Story?","What is class diagram?", "What is operation contract?", "What is Scrum?", "What is Maintenance phase?","What is Scrum Master?", "What is Product Owner?", "What is Sprint?", "What is traceability?","What kind of methodologies do you know?", "What is security by design?", "What is the difference between Sprint backlog and Product backlog?","What is Sprint Planning?", "What is Product Backlog?", "What is daily scrum meeting?","What is review meeting?","What is retrospective meeting?", "What is iterative approach?", "What is agile approach?", "What is process model?", "What is design?", "What is architecture?", "What is case diagram? ", "What is waterfall?", "What are requirements?","What are goals?", "What is start up?", "What is High level design phase?", "What is Low level design phase?", "What is Deployment phase?", "What is Development phase?", "What is Testing phase?", "What is contract?", "What is risk analysis?"};
     mrNoruasQuestions = new string[] { "What is Asp.Net?", "What is MVC model?", "What is WCF?", "What is WebApi?", "What is Razor?", "What is socket?", "What are threads?", "What is thread life cycle?", "What is session?", "What is HTML?", "What is JavaScript?", "What is Fiddler?", "What is JSON?", "What is WSDL?", "What is XML?", "What is a return type?", "What is inheritance?", "What is an object?", "What is C#?", "What are methods?", "What is static?", "What is return type?", "What are parameters?", "What is a class?", "What is abstract?", "What is Sprint?", "What is enum?", "What is a bool/boolean?", "What are operators?", "What are data types?", "What is overload?", "What is override?", "What is an array?", "What is a list?", "What is a dictionary?", "What are loops?", "What are the different types of loops?", "What is a constructor?", "How does If loop work?", "How does While loop work?", "How does Foreach loop work?", "How does For loop work?", "What is a property?", "What is an interface?", "What is a delegate?", "What is polymorphism?", "What is a repository?", "What is LinQ", "What is Lambda?", "What are events?", "What is a binary tree?", "What is an algorithm?" };
}
}
